driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: container
      backend: ssh
      hosts_output: container_hostname
      password: root
      port: 2222
      user: root

platforms:
  - name: ubuntu

suites:
  - name: example
